kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: $HARBOR_HOST/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          ports:
            - name: http-$CONTAINER_PORT
              containerPort: $CONTAINER_PORT
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: pipeline-user-harbor
      affinity: {}
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME
spec:
  ports:
    - name: http-$CONTAINER_PORT
      protocol: TCP
      port: $CONTAINER_PORT
      targetPort: $CONTAINER_PORT
  selector:
    app: $APP_NAME
  type: ClusterIP